name: Smile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Show tool versions
        shell: bash
        run: |
          uname -a || true
          cmake --version
          clang --version || true

      # Config
      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang -DSMILE_DEV=ON -DSMILE_INFO=OFF -DSMILE_WARN=OFF

      - name: Configure (Non-Windows)
        if: runner.os != 'Windows'
        run: cmake -S . -B build -DCMAKE_C_COMPILER=clang -DSMILE_DEV=ON -DSMILE_INFO=OFF -DSMILE_WARN=OFF

      # Build
      - name: Build
        run: cmake --build build --config Debug

      # Run Tests
      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Debug
