name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  baseline:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Show tool versions
        shell: bash
        run: |
          uname -a || true
          cmake --version
          gcc --version || true
          clang --version || true

      # System dependant config
      - name: Configure (Windows, clang + Ninja)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang -DSMILE_DEV=ON -DSMILE_INFO=OFF -DSMILE_WARN=OFF

      - name: Configure (Non-Windows)
        if: runner.os != 'Windows'
        run: cmake -S . -B build -DSMILE_DEV=ON -DSMILE_INFO=OFF -DSMILE_WARN=OFF

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build build

      - name: Build (Non-Windows)
        if: runner.os != 'Windows'
        run: cmake --build build --config Debug

      # Run Smile tests
      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Debug
